[project]
name = "bart-gpu-article"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bartz",
    "catboost>=1.2.10",
    "flatbuffers>=25.12.19",
    "ipython>=9.9.0",
    "matplotlib>=3.10.8",
    "matplotlib-label-lines>=0.8.1",
    "openml>=0.15.1",
    "polars[pandas]>=1.37.1",
    "pytest>=9.0.2",
    "rapidfuzz>=3.14.3",
    "rbartpackages[jax,polars]>=0.2.0",
    "rpy2>=3.6.4",
    "scikit-learn>=1.8.0",
    "tensorstore>=0.1.82",
    "wurlitzer>=3.1.1",
    "xgboost>=3.1.3",
]

[project.optional-dependencies]
cuda12 = ["jax[cuda12]>=0.9.0", "cupy-cuda12x"]
cuda13 = ["jax[cuda13]>=0.9.0", "cupy-cuda13x"]

[project.scripts]
benchmark = "bart_gpu_article.scripts.benchmark:main"
benchmark-plot = "bart_gpu_article.scripts.benchmark_plot:main"
test-rmse = "bart_gpu_article.scripts.test_rmse:main"
test-rmse-plot = "bart_gpu_article.scripts.test_rmse_plot:main"
list-datasets = "bart_gpu_article.scripts.list_datasets:main"
savedata = "bart_gpu_article.scripts.savedata:main"
fullbench = "bart_gpu_article.scripts.fullbench:main"
fullbench-plot = "bart_gpu_article.scripts.fullbench_plot:main"
explore-datasets = "bart_gpu_article.scripts.explore_datasets:main"
save-datasets = "bart_gpu_article.scripts.save_datasets:main"

[tool.ruff.lint]
ignore = ["F722"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.uv.sources]
bartz = { git = "https://github.com/bartz-org/bartz.git", rev = "neurips" }

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
